### ISSUE TITLE
Allow per-domain wildcard link filters

### ISSUE THREAD

**Issue by aecio** [ViDA-NYU/ache#121]
Sometimes it is desired to crawl only URLs that match specific patterns in a domain, and each site contains a different domain.

**Comment by binh-vu** [comment]
It's also very helpful if we could have documentation for LinkClassifier

**Comment by aecio** [comment]
Hi @binh-vu, there is some documentation on how to run a focused crawl using a link classifier and online learning at: http://ache.readthedocs.io/en/latest/tutorial-focused-crawl.html
We also plan to add more detailed documentation as soon as time allows at: http://ache.readthedocs.io/en/latest/crawling-strategies.html#link-classifiers
If you have any more specific question, we kindly ask you to open another issue for that.

**Comment by aecio** [comment]
Documentation for per-domain link filters is available at: http://ache.readthedocs.io/en/latest/link-filters.html
