### ISSUE TITLE
Memory leak on WarcTargetRepository

### ISSUE THREAD

**Issue by aecio** [ViDA-NYU/ache#124]
webarchive-commons' s WARCWriter maintains references to all written records internally in a linked list which causes OutOfMemory error.

**Comment by anudeepti2004** [comment]
Thats a great catch. So this is why the crawler stopped running after 30 mins or so.

**Comment by aecio** [comment]
@anudeepti2004 Yes, that was the reason. It's hard to find this type of problems.

**Comment by aecio** [comment]
Fixed in f01a15d0e10d3b075be6e16629270d57e0778942.
