### ISSUE TITLE
Question about ache.yml user-agent and cookies format

### ISSUE THREAD

**Issue by mkenne11** [ViDA-NYU/ache#135]
I have setup ache to crawl an authenticated site. I am trying to simulate the current firefox browser version.

When I run ache it crawls the unauthenticated site pages however it doesn't authenticate me using the cookie I provided. See ache.yml snippet below.

I exported the cookie directly from firefox and confirmed the login session is still valid in the browser by browsing to the site. I'm wondering if the format for user-agent and cookie that I used is correct. Could you tell me if they look like the correct format?
 
```
crawler_manager.downloader.user_agent.name: A Website
crawler_manager.downloader.user_agent.url: http://awebsite.com
crawler_manager.downloader.user_agent.string: Mozilla/5.0 (Windows NT 6.1; rv:56.0) 
  Gecko/20100101 Firefox/56.0
...

crawler_manager.downloader.cookies:
- domain: awebsite.com
  cookie: domain=awebsite.com; expirationDate=55555666677.111222; hostOnly=true; httpOnly=false;
  name=website_session; path=/; sameSite=no_restriction; secure=false; session=false; storeId=0;
  value=1uic4gg93ufgfg7s8chhhh889; id=1; 
```

**Comment by aecio** [comment]
Yes, it looks correct to me. Do you have any more details that would be helpful to debug it?

**Comment by mkenne11** [comment]
Thanks @aecio. I don't have access to my dev machine atm but when I test next I'll confirm what errors I'm seeing.

I did some research and read that user-agent "name" and "url" are only set by software agents that want to announce themselves to sites they are indexing or accessing in some way. 
https://en.wikipedia.org/wiki/User_agent#User_agent_identification

Is setting user-agent .name & .url properties required in ACHE?

**Comment by aecio** [comment]
AFAIK, I don't think it is strictly required. The setting `user_agent.string` is the value sent as a `User-Agent` HTTP request header. The setting `user_agent.name` and `user_agent.url` are used to create a `user_agent.string` if you don't provide it. I think that if you provide an empty or null `user_agent.string`, you won't send any information.

**Comment by mkenne11** [comment]
Thanks for confirming @aecio. I'll send through the error information when i have access to my machine again.

**Comment by aecio** [comment]
Closing this for now. Please re-open if it is still an issue.
