### ISSUE TITLE
Problem with extracting URL

### ISSUE THREAD

**Issue by binh-vu** [ViDA-NYU/ache#141]
When crawling DBLP: ```http://dblp.dagstuhl.de/db/conf/```, ACHE gets into a loop of URLs, and stuck in it. For example:

1. ```http://dblp.dagstuhl.de/db/conf/?pos=7001%2F```
2. ```http://dblp.dagstuhl.de/db/conf/?pos=7001%2F%2F```
3. ```http://dblp.dagstuhl.de/db/conf/?pos=7001%2F%2F%2F```
4. etc.

I double checked the content of crawled pages, but they don't have any URL ending with ```%2F``` (or ```/```), just ```?pos=7001```

I use ACHE version 0.9.0, docker image: a285012ba763

**Comment by aecio** [comment]
Thanks for reporting this problem. Do you know exactly which page contains the URL ending in  ``?pos=7001``? That would help to debug if there is any bug in the link extractor or somewhere else.

**Comment by binh-vu** [comment]
You can open any page, for example: ```http://dblp.dagstuhl.de/db/conf/``` or
```http://dblp.dagstuhl.de/db/conf/?pos=6901```. I observe it for almost all ```?pos=```. 7001 is just an example.

This is my seed: ```http://dblp.dagstuhl.de/db/conf/?pos=1```
This is my page classifier

```
- "http://dblp\\.dagstuhl\\.de/db/conf/\\?pos=\d+"
- "http://dblp\\.dagstuhl\\.de/db/conf/(?!(index\\.html)?\\?pos).+"
```

I notice it when it has been crawled about 30 thousands pages.

**Comment by aecio** [comment]
Hi @binh-vu, I finally was able to reproduce and track down the root of the problem. I just submitted a fix for the bug. If you still see the problem please reopen the issue. Thanks.
