### ISSUE TITLE
Could not instantiate classifier using config

### ISSUE THREAD

**Issue by Nitin-Panwar** [ViDA-NYU/ache#151]
I am getting below issue while executing the code with default configuration.
![image](https://user-images.githubusercontent.com/19501617/36110831-0f69db26-104a-11e8-8021-7f7f5110398f.png)

**Comment by aecio** [comment]
What ACHE version are you using, and what target classifier model are you using?
We have recently rewritten the target page classifier using a new machine-learning library, which means that page classifier models trained with previous versions will not work with the latest code. Does re-building the model using the same training data solves the issue for you?

**Comment by Nitin-Panwar** [comment]
Thanks for the quick reply. I think you are right, i was using the conda installation with latest code configuration and conda installation of ache was based on last successful build. 
Based on your suggestion i rebuilt the latest repository code and used the same configuration while running and it worked.
