### ISSUE TITLE
(1) deflate/inflate; (2)forum for dialog?

### ISSUE THREAD

**Issue by basd925** [ViDA-NYU/ache#152]
(1) I have a docker image [latest] running. Crawls work.  However, I have been unable to read the data_pages/xxxx-0.deflate file.  (I can read the data_monitor csv files).  I tried "target_storage.data_format.filesystem.compress_data: false" with no change. Any suggestions?

(2) Is there a forum for ache or other place for dialog?  It has taken some blundering about to get as far as running a test crawl!

**Comment by aecio** [comment]
(1) What data format are you using? The flag `target_storage.data_format.filesystem.compress_data: false` will work only if you're using one of the `FILESYSTEM_*` data formats. `FILES` data format is currently always compressed as of now. I usually use the following commands when I want to quickly visualize raw data on terminal:

```
alias deflate="perl -MCompress::Zlib -e 'undef $/; print uncompress(<>)'"
cat data_pages/xxxx-0.deflate | deflate
```
To programmatically read data, you will need something like a InflaterInputStream class in Java or something like zlib in Python or other languages.

(2) Sorry to hear that! There is a Gitter chatroom available for chat: https://gitter.im/ViDA-NYU/ache 
Let us know if you have any suggestions to improve documentation or ease to use.

**Comment by basd925** [comment]
(1) Thank you! Problem was that I uncommented the FILESYSTEM_HTML, but did not comment the FILES lines in the sample ache.yml I retrieved here, so I did not notice that the FILES instruction was over-riding the FILESYSTEM_HTML instruction.

I have zlib installed, so I tried gzip and bzip2 , but no luck.  I will try the command you provided and will eventually connect to my Elasticsearch server.

(2) I had not used docker, but the docker image seemed the best choice to test ache.  But, I was puzzled how to find the "file locations" in the image, especially as my initial runs simply ran help and closed the container.  It is actually straightforward, but depending upon your intended target user, some steps in the structions would be useful:

- install docker.  On my system (openSUSE), docker installs to /run/docker
- system runs in root/admin mode
- docker command line help allows to check for running containers and images
- create an ache directory (my linux install has a specific data partition, so I created at /data/ache, with sub directories /data/ache/config, /data/config/model and /data/data.  Another option might be /var/ache,  /var/ache/config, /data/config/model and /var/data/data.  So, in the docker command to run crawl found in the manual, so $PWD is replaced by "/data/ache", "var/ache" or whatever is chosen.
- in the config directory download the sample ache.yml from git. (For initial test, comment out the 
lines at # Enable this to use the FILES data format and uncomment target_storage.data_format.type: FILESYSTEM_HTML).
- create a seeds.txt in the config directory.  For my test, I merely placed the url of one of my own sites.
- run the command for single site in-depth crawl (Chapter 3 of manual), eg: "docker run -v /data/ache/config/:/config -v /data/ache/data/:/data -p 8080:8080 vidanyu/ache:latest startCrawl -c /config/ -s /config/seeds.txt -o /data/"
-watch directory /data/ache/data/default/ (which will be created).  "/data/ache/data/default/data_pages" will accrue pages, so you can visualize what the crawler is up to.
- make this number a lot smaller if you do not want to accidentally fill up your root partition and disable your computer: "target_storage.visited_page_limit: 10000000"

Be prepared to stop the crawler with "<ctrl>c" on the command line.

(3) I apologize for the lengthy post.  I am very enthusiastic about ache -- I had previously set up an Elasticsearch server with the goal of a project exactly like ache.  Some of my mistakes were: 

- I right-clicked on the sample ache.yml file and sample_seeds files thinking I was saving the actual github files.  But, it turned out instead I was saving the github web page, so I had very odd feedback when I ran the crawl (as you can imagine).
- I generally test crawls against my own webpages to avoid creating a lot of traffic to a known website and risking getting my IP banned.  BUT, I picked one of my own websites that has tons of links off the site, so when I was watching data_pages fill up, before I knew it I had 1490 pages and continuing to grow.
- Because I like easy gui launching, I made a script and a .desktop file to launch ache, running in a terminal window and staying open upon termination.  HOWEVER, this meant I could not use <ctrl>c to stop the crawl.  I thought it would stop by closing the terminal window in which it was running, but no, not so.  I did not think ahead and put I small limit on the depth to crawl, so that was a bit of panic -- I called up the linux system activity/task manager.  The most active thread was a java thread, which did not respond to "end process", so I had to send a "kill" signal.  (Also, I will be adding to my launch script to allow modification of the command line at startup).

**Comment by aecio** [comment]
Thanks for your detailed feedback! We will try to incorporate it in the documentation.
