### ISSUE TITLE
Add Elastic search format for Kafka 

### ISSUE THREAD

**Issue by ashabbir** [ViDA-NYU/ache#155]
Currently kafka supports JSON and CDR31
Add ELASTIC Search Format for Kafka output

**Comment by aecio** [comment]
Configuration of the JSON object format can be changed by adding this config entry to `ache.yml`:

`target_storage.data_format.kafka.format: ELASTIC`

More details on how to use the KAFKA data format is available here: http://ache.readthedocs.io/en/latest/data-formats.html#dataformat-kafka

**Comment by ashabbir** [comment]
```Caused by: com.fasterxml.jackson.databind.exc.InvalidFormatException: Can not deserialize value of type focusedCrawler.target.repository.kafka.KafkaConfig$Format from String "ELASTIC": value not one of declared Enum instance names: [JSON, CDR31]
ache_1           |  at [Source: N/A; line: -1, column: -1] (through reference chain: focusedCrawler.target.repository.kafka.KafkaConfig["target_storage.data_format.kafka.format"])```

**Comment by aecio** [comment]
@ashabbir Seems like you are not using the latest docker image. This is a ache.yml parsing error (previous versions did not suppor the ELASTIC value.) Make sure you run `docker pull vidanyu/ache` and that you are using the `latest` docker tag.
