### ISSUE TITLE
Documentation about maximum depth limit for in-depth crawler

### ISSUE THREAD

**Issue by SukritiSharma** [ViDA-NYU/ache#156]
Documentation missing about setting depth limit when crawler if fetching pages. 
The following configuration to ache.yml in order to specify "how 'far" from the seeds the crawler should go:

Enables "scope" to only crawl pages that belong to domains of seed URLs
link_storage.link_strategy.use_scope: true

Retricts crawler to follow links within a given "hops" of the seeds
link_storage.link_classifier.type: MaxDepthLinkClassifier
**link_storage.link_classifier.max_depth: 0**

**Comment by aecio** [comment]
Thanks @SukritiSharma !  I added a more detailed documentation here: http://ache.readthedocs.io/en/latest/crawling-strategies.html#maxdepthlinkclassifier
