### ISSUE TITLE
How to read .deflate file contents ?

### ISSUE THREAD

**Issue by sheeluee7** [ViDA-NYU/ache#166]
How to read .deflate file contents generated in output  at {output-directory}/default/data_pages/

**Comment by aecio** [comment]
.deflate files are compressed using the deflate algorithm from the zlib library. How to read (decompress) depends on the programming language you are using.

- To programmatically read data, you can use something like the `InflaterInputStream` class in Java or something like `zlib` module in Python or other languages.

- To quickly visualize raw data on the terminal (on Linux or MacOS), I usually use the following commands:

```
alias deflate="perl -MCompress::Zlib -e 'undef $/; print uncompress(<>)'"
cat data_pages/xxxx-0.deflate | deflate
````

After decompressing, the content of the file is a plain text file containing one JSON per line as described in the documentation: http://ache.readthedocs.io/en/latest/data-formats.html#dataformat-files

**Comment by sheeluee7** [comment]
Thanks for the detailed answer !
