### ISSUE TITLE
 Running on Win 7

### ISSUE THREAD

**Issue by tpolo777** [VIDA-NYU/ache#167]
I want to instal and run Ache on Win 7 (64),  hardware (Intel I3 530 2,93 GHz, 4 RAM) , Is it possible ? If so, Is  this installation guidance (http://ache.readthedocs.io/en/latest/install.html) useable for Win 7 ? Thank you for answers )

**Comment by aecio** [comment]
These instructions were not written using Windows and we never tested them on Windows, but it should be possible to run ACHE on Windows using Docker.
