### ISSUE TITLE
Installation on Ubuntu 16.04 failed

### ISSUE THREAD

**Issue by tpolo777** [ViDA-NYU/ache#170]

**Comment by tpolo777** [comment]
> Why have you removed the description? Is the problem solved? If not, can you give more details of the steps you have done?

Sorry, I deleted the description by mistake. Im little stuck trying to install Ache on Linux Ubuntu 16.04. I ve installed JDK 8 and GIT. Should I install satellite projects  described here https://github.com/ViDA-NYU/memex ? I did everything step by step as written in manual ( https://ache.readthedocs.io/en/latest/install.html) , but the command ache isnt available on the terminal.  Can you provide more detailed guide if you have one? My aim is to collect all news issues in a one topic, and find all scientific databases belong to biology domain. Im very thankful for your help)

**Comment by aecio** [comment]
Can you share the output of the commands `echo $ACHE_HOME`, `ls $ACHE_HOME` and `echo $PATH`? You may be setting some of these values incorrectly.

**Comment by tpolo777** [comment]
I ve fixed it myself , but thanks anyway ) The problem was I hadnt  added  ACHE binaries to the PATH environment

**Comment by tpolo777** [comment]
arthur@arthur-System-Product-Name:~/ache$ ache addSeeds -o
----------------------------
ACHE Crawler 0.12.0-SNAPSHOT
----------------------------

Unable to parse the input. Required values for option 'dataOutputPath' not provided
How to fix it ?

**Comment by aecio** [comment]
The command `ache addSeeds` is not necessary anymore and is deprecated. You can set the seeds using the flag `-s` of the `ache startCrawl` command. You can follow one of the tutorials to see an example.

**Comment by aecio** [comment]
I'm closing this since you seem to be have resolved the issue. Please reopen if necessary.

**Comment by tpolo777** [comment]
> I'm closing this since you seem to be have resolved the issue. Please reopen if necessary.
before Ive created (sample_training_data folder at opt/ache/config) and (output_model folder at opt/ache/config) then put pos/neg html files at sample_training_data folder. When running  ache buildModel -c config/sample_config/stop.txt -t sample_training_data -o output_model  
                                                       output > here

arthur@arthur-System-Product-Name:~$ ache buildModel -c config/sample_config/stoplist.txt -t sample_training_data -o output_model
----------------------------
ACHE Crawler 0.12.0-SNAPSHOT
----------------------------

Failed to build model.

java.io.FileNotFoundException: config/sample_config/stoplist.txt (No such file of directory)
	at java.io.FileInputStream.open0(Native Method)
	at java.io.FileInputStream.open(FileInputStream.java:195)
	at java.io.FileInputStream.<init>(FileInputStream.java:138)
	at java.io.FileInputStream.<init>(FileInputStream.java:93)
	at focusedCrawler.util.string.StopListFile.<init>(StopListFile.java:90)
	at focusedCrawler.target.classifier.TargetClassifierBuilder.loadStopwords(TargetClassifierBuilder.java:48)
	at focusedCrawler.target.classifier.TargetClassifierBuilder.<init>(TargetClassifierBuilder.java:41)
	at focusedCrawler.Main$BuildModel.run(Main.java:179)
	at focusedCrawler.Main.main(Main.java:59)
