### ISSUE TITLE
Ache container crashes on EC2 instance after running for sometime

### ISSUE THREAD

**Issue by kumarankitapp** [VIDA-NYU/ache#185]
Trying to crawl using the tor proxy and using the default tor.seed file but the ache container stops with no output.

**Comment by aecio** [comment]
Please post the error log.

**Comment by kumarankitapp** [comment]
![image](https://user-images.githubusercontent.com/45472381/61742987-31216200-ad49-11e9-875a-1831e2efac56.png)


So when trying to run the crawler, i am getting this error. The ache.yml config file and seed.txt is inside the /config folder. not sure where I should be pointing them. Trying to run the crawler without tor proxy

**Comment by snreynolds** [comment]
Closing the issue - we believe the issue was in how we were referencing the ache.yml and seeds.txt
