### ISSUE TITLE
Upgrade npm packages to fix 1047 vulnerabilities in dashboard

### ISSUE THREAD

**Issue by futurityab** [VIDA-NYU/ache#187]
If someone want to do a 'npm audit fix' and commit, it would take care of 1047 vulnerabilities in ache-dashboard.

**Comment by aecio** [comment]
Thanks for the report. Most vulnerabilities are fixed by upgrading `bootstrap`. Others can be fixed when `searchkit` 2.3.3 is released. Fixed in commit 66a12c896c6ce875c520499024a876b3076b6c6a
