### ISSUE TITLE
How to config ache Tor crawler for deal with captcha

### ISSUE THREAD

**Issue by chanwitkepha** [VIDA-NYU/ache#205]
Because I try to search all document but cannot find it. Please suggest, Thank you.

**Comment by aecio** [comment]
ACHE does not support solving captchas automatically. What you could try to do is to solve the captcha manually, collect the cookies from the browser, and then set up ACHE to use the same cookies and user agent collected from the browser.

**Comment by chanwitkepha** [comment]
> ACHE does not support solving captchas automatically. What you could try to do is to solve the captcha manually, collect the cookies from the browser, and then set up ACHE to use the same cookies and user agent collected from the browser. There is a tutorial on how to do this: https://ache.readthedocs.io/en/latest/tutorial-crawling-cookie.html

Thank you for your answer. I will try it again.

**Comment by chanwitkepha** [comment]
> ACHE does not support solving captchas automatically. What you could try to do is to solve the captcha manually, collect the cookies from the browser, and then set up ACHE to use the same cookies and user agent collected from the browser. There is a tutorial on how to do this: https://ache.readthedocs.io/en/latest/tutorial-crawling-cookie.html

I'm already test with both normal web site and Onion Service (Dark Web). It seems work with normal web site but cannot use with web site with onion service. I don't sure what is difference between Onion Domain and Normal (such as .com). Please suggest, Thank you.
