### ISSUE TITLE
Support Elasticsearch 7.x and 8x

### ISSUE THREAD

**Issue by aecio** [VIDA-NYU/ache#206]

**Comment by 3v1lb1t** [comment]
You can manually create the index and import the index template but I don't think that is great for most people who aren't experienced with Elastic. I was trying to find the files that talk specifically about elastic to modify the index information. Can you point me to those so I can test a few things and build out the index/index template that will match with the Elastic 7.x data structures?

**Comment by aecio** [comment]
These are the files related the ES support:
- [ElasticSearchRestTargetRepository.java](https://github.com/VIDA-NYU/ache/blob/master/ache/src/main/java/achecrawler/target/repository/ElasticSearchRestTargetRepository.java) (logic for dealing with indexes is here)
- [ElasticSearchClientFactory.java](https://github.com/VIDA-NYU/ache/blob/master/ache/src/main/java/achecrawler/target/repository/elasticsearch/ElasticSearchClientFactory.java)

Currently, it checks if the index exists, and creates one if no index is found.

**Comment by aecio** [comment]
I believe the main thing that breaks compatibility support ES 7+ is the removal of document types, but I haven't had the time to try to fix it yet: https://www.elastic.co/guide/en/elasticsearch/reference/current/removal-of-types.html
Maybe creating a new "repository" class to support ES 7+ would be the easiest. Anyway, please let us know if you manage to make it work. A PR for this would be very welcome.

**Comment by 3v1lb1t** [comment]
I will absolutely let you know. With the document types being removed, it actually makes it much simpler to create index templates.

**Comment by 3v1lb1t** [comment]
The easiest way to overcome this would be to configure the elastic instance for dynamic mapping. Then you are scalable unless they get rid of that functionality with I highly doubt.

**Comment by chanwitkepha** [comment]
> I believe the main thing that breaks compatibility support ES 7+ is the removal of document types, but I haven't had the time to try to fix it yet: https://www.elastic.co/guide/en/elasticsearch/reference/current/removal-of-types.html Maybe creating a new "repository" class to support ES 7+ would be the easiest. Anyway, please let us know if you manage to make it work. A PR for this would be very welcome.

Hello, My Boss in office also try to correct this problem too. I already test with Elasticsearch 7.16.2 and  It work. So I hope this can help, Thank you.

![elasticsearch-7](https://user-images.githubusercontent.com/45688421/151296536-59d78b55-5392-47b6-8be2-feb21c2d04bf.jpg)

**Comment by aecio** [comment]
Great, thanks. Did you have the chance to test if the web search interface works as well?

**Comment by chanwitkepha** [comment]
Below this is the file which my boss edit for support ElasticSearch 7.x.  

[ElasticSearchRestTargetRepository.zip](https://github.com/VIDA-NYU/ache/files/7958378/ElasticSearchRestTargetRepository.zip)

**Comment by JuliusHenke** [comment]
I have made a pull request #282 and implemented some of the suggestions from @chanwitkepha. The indexing works great but the web search interface will not work without further changes.

**Comment by aecio** [comment]
Just merged it. Thanks, @JuliusHenke and @chanwitkepha!

**Comment by aecio** [comment]
PR #341 adds support to the search interface and concludes this issue.
