### ISSUE TITLE
Crawler Execution Failed

### ISSUE THREAD

**Issue by fatimasadiq** [VIDA-NYU/ache#207]
Hi 
I'm new to ACHe crawler and  trying to run the sample to see how the crawler is collecting data then i can run myown bnut its giving me below error. I'm running on centos7 with docker.

Please help.

![image](https://user-images.githubusercontent.com/8520057/124563222-85e01980-de48-11eb-962a-999632ae9de7.png)

**Comment by fatimasadiq** [comment]
Hi now im getting attached while running the crawler nothing is downloaded.
<img width="1390" alt="Screenshot 2021-07-06 at 14 49 03" src="https://user-images.githubusercontent.com/8520057/124612592-218a7d80-de7b-11eb-85c5-b820c5c0982b.png">

**Comment by aecio** [comment]
For the first problem, you were probably configuring the docker volume at the wrong directory, but you seem to have already fixed it.

For the second screenshot, the crawling is ignoring non-english pages by default. You can disable this feature by adding the following on the ache.yml file:

```yaml
# Store only pages that contain english text using language detector
target_storage.english_language_detection_enabled: false
```

The sample config file at https://github.com/VIDA-NYU/ache/blob/master/config/sample_config/ache.yml has other configurations that my be useful.

**Comment by aecio** [comment]
The crawler also ignores non-HTML content by default (e.g., jpg images as seen in the log). To allow other types of content, you need to add the following config on ache.yml (including other mime-types that you need):

```
crawler_manager.downloader.valid_mime_types:
 - text/xml
 - text/html
 - text/plain
 - application/x-asp
 - application/xhtml+xml
 - application/vnd.wap.xhtml+xml
```

**Comment by fatimasadiq** [comment]
Dear Aecio,

Thank you for the response. Let me try this and I will come back to this thread. so please don't close it.

**Comment by aecio** [comment]
Closing this issue. Feel free to open another issue if you find other problems.
