### ISSUE TITLE
Test Page Classifier against given page

### ISSUE THREAD

**Issue by jim113** [VIDA-NYU/ache#208]
I was trying to test the trained model for page classification from ACHE using the command:

"ache run TargetClassifierTester --input-file {html-file} --model {model-config-directory}"
As it appears in the documentation but system could not run it.

Does this command no longer exist? How can I test the trained classifier against some URLs?

**Comment by aecio** [comment]
The command still exists. However, this tool was recently moved to the new module `ache-tools` (in the master branch). For now, if you are using the latest version from the master branch you must build the `ache-tools` module using:

```
cd ache-tools
../gradlew installDist
```

The binary for ache-tools will be located at build/install/ache-tools/bin/ache-tools, so you can run"

```
build/install/ache-tools/bin/ache-tools
build/install/ache-tools/bin/ache-tools run TargetClassifierTester
```

**Comment by aecio** [comment]
This command is now available in the main ache app and the docs are up-to-date:
```
ache testTargetClassifier --input-file {html-file} --model {model-config-directory}
```
