### ISSUE TITLE
ACHE crawls stall if given too few seeds

### ISSUE THREAD

**Issue by ahmadia** [ViDA-NYU/ache#21]
The ACHE crawl will be "running" as if it is still doing things but it is actually just spinlocked.

Steps to reproduce:
* start a new ACHE crawl with 3 seeds and run it.

How many seeds are needed?

**Comment by julianafreire** [comment]
Very likely, the crawler ran out of links to follow. But we should have a warning message to indicate when this happens, and cleanly stop the crawling processes (or maybe give users the ability to provide more seeds?)
WRT the number of seeds, it depends on the domain and seeds -- if the pages in the domain are highly connected and the seeds contain enough links, few seeds should be sufficient -- but 3 seems too few.
