### ISSUE TITLE
TorProxy not connecting

### ISSUE THREAD

**Issue by 3v1lb1t** [VIDA-NYU/ache#220]
I am currently working on a project to index over tor. I have the docker-compose file and ache file configured but it appears that torproxy is failing to connect to a circuit which is causing the crawler to abort downloads with Fetch_Duration_Exceeded. I have tried a few different configurations with the docker network as well as the virtual machine where the crawler is running. I started a VPN on the VM to attempt to help but that didn't work. I tried installing tor on the virtual machine and torifying all commands through the shell which didn't work either.

**Comment by aecio** [comment]
Does the example in https://github.com/VIDA-NYU/ache/tree/master/config/config_docker_tor work fine?

**Comment by 3v1lb1t** [comment]
It appears fetch duration is too short. I did a local install of Ache with a docker torproxy running and was able to get successful requests crawled. When I was testing this, it took quite some time for the Tor circuit to be created. I'm not sure exactly how long but upwards of 2 minutes. I basically just started the torproxy machine, pointed my browser to use that as a proxy, then waited for something to load through it.

**Comment by 3v1lb1t** [comment]
It appears fetch duration is too short. I did a local install of Ache with a docker torproxy running and was able to get successful requests crawled. When I was testing this, it took quite some time for the Tor circuit to be created. I'm not sure exactly how long but upwards of 2 minutes. I basically just started the torproxy machine, pointed my browser to use that as a proxy, then waited for something to load through it.

**Comment by aecio** [comment]
There are some fetch timeout configurations that you can include in ache.yml that may help:
 ```
crawler_manager.downloader.httpclient.socket_timeout: 30000
crawler_manager.downloader.httpclient.connection_timeout: 30000
crawler_manager.downloader.httpclient.connection_request_timeout: 60000
```
All configurations for the downloader are listed in this class: [HttpDownloaderConfig.java](https://github.com/VIDA-NYU/ache/blob/master/ache/src/main/java/achecrawler/crawler/async/HttpDownloaderConfig.java)

**Comment by 3v1lb1t** [comment]
Perfect, thank you

**Comment by aecio** [comment]
Closing this issue. Documentation regarding timeouts has been added to the docs: https://ache.readthedocs.io/en/latest/http-fetchers.html#setting-connection-timeouts
