### ISSUE TITLE
I can not find any folder like  buid in ache folder

### ISSUE THREAD

**Issue by smitbhojani5555** [VIDA-NYU/ache#273]
export ACHE_HOME="{path-to-cloned-ache-repository}/ache/build/install/ache"
export PATH="$ACHE_HOME/bin:$PATH"

This is not working  and  this path doesn't exist

**Comment by aecio** [comment]
That path is created only after the Gradle build is completed successfully. Also, of course, make sure you replace `{path-to-cloned-ache-repository}` with the correct path where you downloaded the source code.
