### ISSUE TITLE
Issue in Start Ache Crawler

### ISSUE THREAD

**Issue by smitbhojani5555** [VIDA-NYU/ache#276]
Hi , I am using  windows 11  and i do all the setup for ache 
and  we try to run ache  by start crawler for gradle but it is  showing incorrect command ""Ache"
So please guide me how can start carwler using gradle set up without using docker

**Comment by aecio** [comment]
Unfortunately, I do not have access to a Windows machine and we don't have specific instructions on how to set up ACHE on Windows in the documentation.
