### ISSUE TITLE
Enable Javascript using TorProxy

### ISSUE THREAD

**Issue by hackrx** [VIDA-NYU/ache#314]
Hello team, 
I am trying to crawl .onion sites and I am getting this in all the HTML files: 
```
<body><noscript><strong>We're sorry but Blog doesn't work properly without JavaScript enabled. Please enable it to continue.</strong></noscript><div id="app"></div><script src="/js/chunk-vendors.a7f219e8.js"></script><script src="/js/app.9b916c85.js"></script></body>
```
Is there any way to allow javascript execution?
I used this guide to setup ACHE: 
https://ache.readthedocs.io/en/latest/tutorial-crawling-tor.html

**Comment by aecio** [comment]
No, unfortunately, javascript execution is not yet supported.
