### ISSUE TITLE
Support standard WARC file format

### ISSUE THREAD

**Issue by aecio** [ViDA-NYU/ache#64]
WARC is a standardized file format used for storing web crawl data. It's widely used for storing large scale web data collections such as CommonCrawl and ClueWeb12.

WARC ISO 28500 draft is available at: http://bibnum.bnf.fr/warc/WARC_ISO_28500_version1_latestdraft.pdf

**Comment by VickySteeves** [comment]
@aecio I have a very good friend who works at Internet Archive if you want to connect. He's all about WARCing :wink:

**Comment by aecio** [comment]
@VickySteeves Thanks! I'll let you know if I have any questions!

**Comment by aecio** [comment]
Fixed in PR #117.
