### ISSUE TITLE
Periodic recrawling of sitemaps.xml to discover new links

### ISSUE THREAD

**Issue by aecio** [ViDA-NYU/ache#73]
ACHE should be able to periodically recrawl sitemap.xml files to discover recently added links.

**Comment by julianafreire** [comment]
Do forum sites usually maintain a sitemap.xml?

**Comment by aecio** [comment]
I'm not aware statistics of the percentage of web sites that contain sitemaps, but from my experience I would say that a large portion of sites have it. Most content management systems (like Wordpress) and forum specific software (like phpBB and vBulletin ) support sitemaps.

**Comment by julianafreire** [comment]
I gather you will be collecting information about which sites have this or not as you crawl. It will be interesting to analyze this info.
