### ISSUE TITLE
Using cookie to simulate user login

### ISSUE THREAD

**Issue by kienpt** [ViDA-NYU/ache#81]
The goal is to crawl websites that require user login. A simple way to do that is using cookie returned by the target site after users sign-in from a browser. To do: 
- Allow users to add cookies of given sites to ACHE configuration file. 
- ACHE adds the provided cookies into the future requests to the corresponding sites. 
Note that we also need to handle the expiration date of the cookies. We can separate this to another issue.

**Comment by kienpt** [comment]
@aecio @julianafreire: So the problem is because of user-agent string. Each cookie is paired with an user-agent string, so we must use the user-agent string from the browser where we get the user-agent string. Note that different browsers and versions have slightly different user-agent strings (Also the way ACHE is handling user-agent string slightly changes it). In fact, if we use a wrong pair of user-agent string and cookie, web server will response a new (authenticated) cookie associated with the wrong user-agent string. We then need to replace the old cookie by this new one in order to continue the authenticated session.

**Comment by aecio** [comment]
@kienpt @julianafreire I committed a change that allows the user to configure the exact `User-Agent` string using a config as in the following example:
```yaml
crawler_manager.downloader.user_agent.string: Mozilla/5.0 (Macintosh; Intel Mac OS X 10_12_5) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/58.0.3029.110 Safari/537.36
```
I am merging the changes that @kienpt did for cookies, and was able to crawl one forum that uses phpBB CMS. I should commit and push to branch master soon.
