### ISSUE TITLE
problem with Docker installation

### ISSUE THREAD

**Issue by julianafreire** [ViDA-NYU/ache#94]
Docker installation did not work. See log below.

ENG-JF1870-001:ACHE juliana$ docker run -p 8080:8080 vidanyu/ache:latest
Unable to find image 'vidanyu/ache:latest' locally
latest: Pulling from vidanyu/ache
10a267c67f42: Pull complete 
fb5937da9414: Pull complete 
9021b2326a1e: Pull complete 
8c6c40e9ec4f: Pull complete 
7a63e1725461: Pull complete 
79e8ed83f43a: Pull complete 
161cbb85a481: Pull complete 
a479609da9c8: Pull complete 
e32f81724ea4: Pull complete 
e78ab5a05d98: Pull complete 
33e3953c92ac: Pull complete 
32b376f2ef99: Pull complete 
Digest: sha256:074dad5adae2867da5ae24967db2c6f66afd2e791b4a60da1ff177ace65404f6
Status: Downloaded newer image for vidanyu/ache:latest
docker: Error response from daemon: driver failed programming external connectivity on endpoint brave_kirch (14ce1e77d7c3ce2617f784d166417900bbc1b29a9b0307cb971b0a11ad91729f): Bind for 0.0.0.0:8080 failed: port is already allocated.
ERRO[0120] error getting events from daemon: net/http: request canceled

**Comment by aecio** [comment]
You probably already have something your machine running on port 8080:

    0.0.0.0:8080 failed: port is already allocated.

You need to stop whatever is running on port 8080 there or specify another port for ACHE like 9090:

    docker run -p 9090:8080 vidanyu/ache:latest

**Comment by aecio** [comment]
The parameter `-p 9090:8080` instructs docker to bind the container port 8080 (that ACHE will use inside the container) to the port 9090 in your local host (9090 needs to be available in your machine).
