### ISSUE TITLE
documentation: installation -- there is no /opt on macos

### ISSUE THREAD

**Issue by julianafreire** [ViDA-NYU/ache#96]
In the install from source, you say:
which will generate an installation package under ache/build/install/. To install ACHE binaries into /opt and make it available on the command-line run:

There is no /opt on macos.

To make this simple, can we just refer to the directory where ACHE was installed? It could be ~/Applications on mac, or something else on Linux. For example, 

"echo 'export ACHE_HOME=<install_dir>/build/install/ache

**Comment by aecio** [comment]
Yes, ACHE_HOME can be any directory.
